os: linux
dist: trusty
group: edge
language: c
branches:
  except:
  - "/^.*-automated-build$/"
  - "/^[0-9]+\\.[0-9]+\\.[0-9]+$/"
env:
  global:
  - secure: vBTSL34BDPxDilKUuTXqU4CJ26Pv5hogD2nghatkxSQkI1/jbdnLj/DQdPUrMJFDIY6TK3AltsBx72MaMsLQ1JO/Ou24IeHINHXzUC1FlS9yQa48cpxnhX5kzXNyGs3oa0qaFbvnr7RgYRWtmD52n4bIZuSuW+xpBv05x2OCizdT2ZonH33nATaHGFasxROm4qYZ241VfzcUv766V6RVHgL4x9V08warugs+RENVkfzxxwhk3NmkrISabze0gSVJLHBPHxroZC6EUcf/ocobcuDrCwFqtEt90i7pNIAFUE7gZsN2uE75LmpzAWin21G7lLPcPL2k4FJVd8an1HiP2WmscJU6U89fOfMb2viObnKcCzebozBCmKGtHEuXZo9FcReOx49AnQSpmESJGs+q2dL/FApkTjQiyT4J6O5dJpoww0/r57Wx0cmmqjETKBb5rSgXM51Etk3wO09mvcPHsEwrT7qH8r9XWdyCDoEn7FCLX3/LYnf/D4SmZ633YPl5gv3v9XEwxR5+04akjgnvWDSNIaDbWBdxHNb7l4pMc+WR1bwCyMyA7KXj0RrftEGOrm9ZRLe6BkbT4cycA+j77nbPOMcyZChliV9pPQos+4TOJoTzcK2L8yWVoY409aDNVuAjdP6Yum0R2maBGl/etLmIMpJC35C5/lZ+dUNjJAM=
  - MAKEFLAGS="-j3 --output-sync"
services:
  - docker
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty-7
    packages:
    - pandoc
    - diffutils
    - dos2unix
    - doxygen
    - clang-format-7
    - libstdc++-7-dev
install:
  - npm install -g moxygen
script:
  - git rev-parse --short HEAD
  - git diff --name-only HEAD $TRAVIS_BRANCH
  - bash util/travis_test.sh
  - bash util/travis_build.sh
  - bash util/travis_docs.sh
after_script:
  bash util/travis_compiled_push.sh
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/afce403d65f143dfac09
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
before_deploy:
- zip eivy.zip ergodox_ez_eivy.hex
deploy:
  provider: releases
  api_key:
    secure: JpaTdosL+IIQvGiwYrPsREd+hxW6Rt0LMANP9GQbt1ZOo3K0RQRc7RcuVjaWhmEo96b2p7mw2S3V8ZpdMtgV7PkPxagCtCjCBI5JmEzhQw/Z+ihDo+vDgeiXrPSpe+tlyy43vr4pjovoOkrkydinLX9Y1KsGCK6Lf5vlxXm6bLgPiJj31jSYHre1YZvQptee+4+ZiyWnBfxU+RL+jBFuHS1zL6FrW1yIYaXkLdBPQT2ol3URrt0jEbRb14D4AoyOFMJsfvXTWsZ+oOtmR3YA3Vrz9jdrsbrRlC1866g3RZfy7Oui9lWn24QqjGgrW8nfqCz3Sz8nwIU59kOqTnn35hCHEAQCf3nNJqE2ArH32uK8j8TQ3akJrybcKSTS6KJadnUAWRDCGhOBsvmwGfN1eeCLtYU62/aTw9L+QjEh9mP5kXJFn91E56h868CE3cHxAgfJZ5PR2IeUHkCd5T7VMjQJh9mv5/OwG7RVxmviTnCKnAKKEcdl4FMu4OfL+VX2tO0/W2IvuZkWvvu4tWZ6Ykc6MfS9RP4nZOBQc0YeSrc7NJ328WR6rZsFK4cpYnTdyUa2DxxZzoT6HgE9oQgZW1RD+YS5bmCjbOYXTSQfy6VfW4h58h2lPnuF4IkxrCQodip+uO5CIyTa4qsyCv42Ifki7GJGDiqpQ0Gjz/JUIL8=
  file: eivy.zip
  skip_cleanup: true
  on:
    repo: Eivy/qmk_firmware
    all_branchies: true
    tags: true
